name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build artifact'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build artifact
        run: tar -cz artifact.tar .
      
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.tar


  deploy:
      name: 'Deploy to Production'
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: .

      - name: Copy artifact via SCP to server
        uses: appleboy/scp-action@v0.1.7
        with:
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          source: artifact.tar
          target: /app/server

      - name: Start deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /app/server
            tar -xvf artifact.tar

            docker stack deploy -c ./traefik/docker-compose.yml traefik